### ISSUE TITLE
[Breaking change] Klipper v0.13.0-515-g85ccd1d9

### ISSUE THREAD

**Issue by AcrimoniousMirth** [viesturz/klipper-toolchanger#147]
Klipper `v0.13.0-515-g85ccd1d9` has a breaking change:

```Internal error during connect: HomingViaProbeHelper.__init__() missing 1 required positional argument: 'param_helper'```

**Comment by AcrimoniousMirth** [comment]
```
Traceback (most recent call last):
  File "/home/manta/klipper/klippy/klippy.py", line 130, in _connect
    self._read_config()
    ~~~~~~~~~~~~~~~~~^^
  File "/home/manta/klipper/klippy/klippy.py", line 123, in _read_config
    self.load_object(config, section_config.get_name(), None)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/manta/klipper/klippy/klippy.py", line 112, in load_object
    self.objects[section] = init_func(config.getsection(section))
                            ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/manta/klipper/klippy/extras/tool_probe.py", line 174, in load_config_prefix
    return ToolProbe(config)
  File "/home/manta/klipper/klippy/extras/tool_probe.py", line 26, in __init__
    self.endstop = self.printer.load_object(config, "tool_probe_endstop")
                   ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/manta/klipper/klippy/klippy.py", line 112, in load_object
    self.objects[section] = init_func(config.getsection(section))
                            ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/manta/klipper/klippy/extras/tool_probe_endstop.py", line 248, in load_config
    return ToolProbeEndstop(config)
  File "/home/manta/klipper/klippy/extras/tool_probe_endstop.py", line 25, in __init__
    self.homing_helper = probe.HomingViaProbeHelper(config, self.mcu_probe, self.param_helper)
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HomingViaProbeHelper.__init__() missing 1 required positional argument: 'param_helper'
```

**Comment by jeffhengesbach** [comment]
Hit this today after updating klipper to v0.13.0-521-gca7d9008. Following

**Comment by viesturz** [comment]
Should be fixed, see #151 please reopen if not so.
